S05 us153 kingdoms
WildCodeSchool/expenssion-one-backend pull request #7
Opened 2024-07-06 13:04 UTC by boubseb

2024-07-06 13:22 UTC, OCR-VH-DevWeb approved these changes
Approved

2024-07-08 09:13 UTC, Benja-san requested changes

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/City.java
> +    public void setId(Long id) {
remove setter for id

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Belief.java
> +    public void setId(Long id) {
remove setter for id

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Divinity.java
> +    public void setId(Long id) {
remove setter for id

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Divinity.java
> +    private String effects;
if it is a string, call it singular

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Divinity.java
> +    private String statistics;
if it is a string, call it singular

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Divinity.java
> +    private String effects;
If it is a list, use List type

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Kingdom.java
> +    public void setId(Long id) {
remove setter for id

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/entity/Region.java
> +    public void setId(Long id) {
remove setter for id

2024-07-08 09:13 UTC, Benja-san commented on src/main/java/com/example/demo/repository/BeliefRepository.java
> +public interface BeliefRepository extends JpaRepository<Belief, Long> {
usez repository annotation

2024-07-08 15:12 UTC, closed without merging