S05 us180 user entity
WildCodeSchool/expenssion-one-backend pull request #9
Opened 2024-07-07 14:44 UTC by boubseb

2024-07-08 10:01 UTC, OCR-VH-DevWeb approved these changes

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/language.json
> +    {"name":"Minérale","description":"compréhension de la terre, roche, permet de détecter deséboulements , transmission du savoir, histoire"},
warning miss space "des éboulements"

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/language.json
> +    {"name":"Langue de Comptoir","description":"patois dérivé du commun qui resteincompréhensible si tu ne le parles pas"},
warning miss space

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/language.json
> +    {"name":"Langue de terrain","description":" langage militaire codéifié qui s’applique la gestuelleet le parler"},
warning miss space

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/language.json
> +    {"name":"Commun","description":"langue que tout le monde parle, générale"},
You change the syntax of description miss maj on the beginning and ponctuation in the end...

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/race.json
> +        {"name":"Angélique","description":"angue des anges"}
Miss "l" of langue des Anges

2024-07-08 10:01 UTC, OCR-VH-DevWeb commented on src/main/resources/data/race.json
> +    },
the url are not completed with good link of image

2024-07-09 12:54 UTC, Benja-san requested changes

2024-07-09 12:54 UTC, Benja-san commented on src/main/java/com/example/demo/ExpenssionOne.java
> +		// DbService dbService = ctx.getBean(DbService.class);
remove dead code or useless blocks

2024-07-09 12:54 UTC, Benja-san commented on src/main/java/com/example/demo/controller/UserController.java
> +      @GetMapping("user/{id}")
use token to avoid user consultaiton by anybody

2024-07-09 12:54 UTC, Benja-san commented on src/main/java/com/example/demo/service/UserService.java
> +        this.userRepository.save(user);
hash password !

2024-07-09 12:54 UTC, Benja-san commented on src/main/java/com/example/demo/service/UserService.java
> +        if (user.getPassword().equals(oldPassword)) {
hash password !

2024-07-10 10:32 UTC, Benja-san approved these changes

2024-07-10 10:39 UTC, merged